# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cda19add5c2d4e56020cdcf9268074c11c7693fa30b03ced09e7464e1da15f846bd7590720e40ef54606be8f92f9aeaea01432581adabd727a0bc1abea220991

test:
  secret_key_base: 30b83c9c401293027f4c9a4877fc85c1f8df2801f7d60e6e62f23ae5b02574227c2158e7b325767748cf7152b8077312c6473f82122fd542d5964944c7e1b37e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
